"""add columns to appt

Revision ID: 939d53e0a7c4
Revises: 51bbdc47fc5b
Create Date: 2024-08-06 10:48:10.327910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '939d53e0a7c4'
down_revision = '51bbdc47fc5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('doctor_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('datetime', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_appointments_table_doctor_id_doctors_table'), 'doctors_table', ['doctor_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments_table', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_appointments_table_doctor_id_doctors_table'), type_='foreignkey')
        batch_op.drop_column('datetime')
        batch_op.drop_column('doctor_id')

    # ### end Alembic commands ###
